#2.1 Sorting function
js-tasks-ru/js-20220905_anfim pull request #2
Opened 2022-09-08 15:12 UTC by GENsf

Make sorting function for array of string

2022-09-08 15:13 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-08 15:36 UTC, anfim-sn commented
PR упал с ошибкой в тесте на 'should correctly sort strings for mixed "en" and "ru" locales'
При проверке тестами в моем репозитории ошибок не было
![изображение](https://user-images.githubusercontent.com/85647236/189164262-1022287b-5c70-406f-84c6-4cad07f81457.png)

2022-09-09 20:53 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let sortedArr = arr.slice().sort((a, b) => {
проверьте использование `let/const`
все переменные тут должны быть `const`

2022-09-09 20:54 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return aLow.localeCompare(bLow);
проверьте какие параметры может принимать `localeCompare`
подсказка: для того чтобы не падали тесты на Github, следует передать массив локалей: `['ru', 'en']`

2022-09-09 20:54 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return sortedArr.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-09-09 20:55 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    let aLow = a.toLowerCase();
метод `toLowerCare` в решении нет необходимости использовать

2022-09-09 20:55 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-09-10 07:41 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-10 08:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-09-10 08:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-09-11 15:25 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    const sortedAscArr = arr.slice().sort((a, b) => {
строка 9-11 дублируют строки 14-16, это следует исправить!

2022-09-11 15:26 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  const filterArr = Object.entries(obj).filter((elem) => {
👍 good

2022-09-11 15:26 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-09-11 16:48 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-12 16:44 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
>        return a.localeCompare(b, ['ru', 'en'], {caseFirst: 'upper'});
вот эту операцию `a.localeCompare(b, ['ru', 'en'], {caseFirst: 'upper'});` можно вынести в функцию:

```
const compare = (first, second) => a.localeCompare(b, ['ru', 'en'], {caseFirst: 'upper'});
```
и просто вызывать с разным порядком аргументов:
```
`compare(a, b)` или `compare(b, a)`

2022-09-12 16:44 UTC, dosandk approved these changes
good 👍

2022-09-12 16:44 UTC, merged